apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: ${LOKI_URL}
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: "trace_id=([a-fA-F0-9]+)"
          url: '$${__value}'
          datasourceUid: tempo
